export interface Feature {
  id: number;
  name: string;
  description: string;
  category: string;
  command?: string;
}

export const featureCategories = [
  'Productivity',
  'Communication',
  'Information',
  'Entertainment',
  'Smart Home',
  'Health & Fitness',
  'Finance',
  'Travel',
  'Education',
  'Security',
  'System Control',
  'Creative',
  'Business',
  'Social Media',
  'Shopping',
  'Weather & Environment',
  'Navigation',
  'Personal Assistant',
  'Data Analysis',
  'Automation',
];

export const features: Feature[] = [
  // Productivity (30 features)
  { id: 1, name: 'Set Reminder', description: 'Create time-based reminders', category: 'Productivity', command: 'remind me to' },
  { id: 2, name: 'Create Calendar Event', description: 'Schedule meetings and events', category: 'Productivity', command: 'schedule' },
  { id: 3, name: 'Set Timer', description: 'Countdown timer for tasks', category: 'Productivity', command: 'set timer' },
  { id: 4, name: 'Set Alarm', description: 'Wake-up and notification alarms', category: 'Productivity', command: 'set alarm' },
  { id: 5, name: 'Task Management', description: 'Create and manage to-do lists', category: 'Productivity', command: 'add task' },
  { id: 6, name: 'Note Taking', description: 'Quick voice-to-text notes', category: 'Productivity', command: 'take note' },
  { id: 7, name: 'Document Scanner', description: 'Scan and OCR documents', category: 'Productivity', command: 'scan document' },
  { id: 8, name: 'Meeting Scheduler', description: 'Find optimal meeting times', category: 'Productivity', command: 'schedule meeting' },
  { id: 9, name: 'Pomodoro Timer', description: '25-minute focus sessions', category: 'Productivity', command: 'start pomodoro' },
  { id: 10, name: 'Time Tracker', description: 'Track time spent on tasks', category: 'Productivity', command: 'track time' },
  { id: 11, name: 'Project Manager', description: 'Manage project milestones', category: 'Productivity', command: 'create project' },
  { id: 12, name: 'Habit Tracker', description: 'Build and track habits', category: 'Productivity', command: 'track habit' },
  { id: 13, name: 'Goal Setting', description: 'Set and track personal goals', category: 'Productivity', command: 'set goal' },
  { id: 14, name: 'Daily Planner', description: 'Plan your daily schedule', category: 'Productivity', command: 'plan day' },
  { id: 15, name: 'Weekly Review', description: 'Review weekly accomplishments', category: 'Productivity', command: 'weekly review' },
  { id: 16, name: 'Focus Mode', description: 'Block distractions', category: 'Productivity', command: 'enable focus' },
  { id: 17, name: 'Priority Matrix', description: 'Prioritize tasks by urgency', category: 'Productivity', command: 'prioritize tasks' },
  { id: 18, name: 'Deadline Tracker', description: 'Monitor upcoming deadlines', category: 'Productivity', command: 'show deadlines' },
  { id: 19, name: 'Workspace Organizer', description: 'Organize digital workspace', category: 'Productivity', command: 'organize workspace' },
  { id: 20, name: 'Quick Capture', description: 'Instant idea capture', category: 'Productivity', command: 'capture idea' },
  { id: 21, name: 'Template Manager', description: 'Create reusable templates', category: 'Productivity', command: 'create template' },
  { id: 22, name: 'Keyboard Shortcuts', description: 'Custom productivity shortcuts', category: 'Productivity', command: 'create shortcut' },
  { id: 23, name: 'Batch Processing', description: 'Process multiple tasks at once', category: 'Productivity', command: 'batch process' },
  { id: 24, name: 'Context Switching', description: 'Switch between work contexts', category: 'Productivity', command: 'switch context' },
  { id: 25, name: 'Energy Level Tracker', description: 'Track personal energy levels', category: 'Productivity', command: 'log energy' },
  { id: 26, name: 'Deep Work Sessions', description: 'Schedule deep work blocks', category: 'Productivity', command: 'deep work' },
  { id: 27, name: 'Interruption Manager', description: 'Handle interruptions gracefully', category: 'Productivity', command: 'log interruption' },
  { id: 28, name: 'Review Scheduler', description: 'Schedule periodic reviews', category: 'Productivity', command: 'schedule review' },
  { id: 29, name: 'Procrastination Buster', description: 'Combat procrastination', category: 'Productivity', command: 'start task now' },
  { id: 30, name: 'Achievement Logger', description: 'Log daily achievements', category: 'Productivity', command: 'log achievement' },

  // Communication (25 features)
  { id: 31, name: 'Send Email', description: 'Compose and send emails', category: 'Communication', command: 'send email' },
  { id: 32, name: 'Send Message', description: 'Send text messages', category: 'Communication', command: 'send message' },
  { id: 33, name: 'Make Call', description: 'Initiate phone calls', category: 'Communication', command: 'call' },
  { id: 34, name: 'Video Call', description: 'Start video conferences', category: 'Communication', command: 'video call' },
  { id: 35, name: 'Voice Mail', description: 'Check voice messages', category: 'Communication', command: 'check voicemail' },
  { id: 36, name: 'Contact Manager', description: 'Manage contact information', category: 'Communication', command: 'add contact' },
  { id: 37, name: 'Group Message', description: 'Send messages to groups', category: 'Communication', command: 'message group' },
  { id: 38, name: 'Email Filter', description: 'Organize email inbox', category: 'Communication', command: 'filter emails' },
  { id: 39, name: 'Auto Reply', description: 'Set automatic responses', category: 'Communication', command: 'set auto reply' },
  { id: 40, name: 'Transcript Generator', description: 'Transcribe conversations', category: 'Communication', command: 'transcribe' },
  { id: 41, name: 'Language Translator', description: 'Translate messages', category: 'Communication', command: 'translate to' },
  { id: 42, name: 'Spam Detector', description: 'Filter spam messages', category: 'Communication', command: 'detect spam' },
  { id: 43, name: 'Read Messages', description: 'Read messages aloud', category: 'Communication', command: 'read messages' },
  { id: 44, name: 'Conference Manager', description: 'Manage conference calls', category: 'Communication', command: 'start conference' },
  { id: 45, name: 'Chat Bot', description: 'Automated chat responses', category: 'Communication', command: 'enable chatbot' },
  { id: 46, name: 'Emergency Contact', description: 'Quick emergency calls', category: 'Communication', command: 'emergency call' },
  { id: 47, name: 'Follow-up Reminder', description: 'Remind to follow up', category: 'Communication', command: 'remind follow-up' },
  { id: 48, name: 'Meeting Minutes', description: 'Record meeting notes', category: 'Communication', command: 'record minutes' },
  { id: 49, name: 'Voice Broadcast', description: 'Broadcast voice messages', category: 'Communication', command: 'broadcast message' },
  { id: 50, name: 'Sentiment Analysis', description: 'Analyze message tone', category: 'Communication', command: 'analyze sentiment' },
  { id: 51, name: 'Reply Suggestions', description: 'Smart reply suggestions', category: 'Communication', command: 'suggest reply' },
  { id: 52, name: 'Contact Sync', description: 'Sync across devices', category: 'Communication', command: 'sync contacts' },
  { id: 53, name: 'Communication Stats', description: 'View communication analytics', category: 'Communication', command: 'show stats' },
  { id: 54, name: 'Priority Inbox', description: 'Prioritize important messages', category: 'Communication', command: 'show priority' },
  { id: 55, name: 'Scheduled Messages', description: 'Schedule message delivery', category: 'Communication', command: 'schedule message' },

  // Information (30 features)
  { id: 56, name: 'Web Search', description: 'Search the internet', category: 'Information', command: 'search for' },
  { id: 57, name: 'Wikipedia Lookup', description: 'Quick Wikipedia facts', category: 'Information', command: 'wikipedia' },
  { id: 58, name: 'News Updates', description: 'Latest news headlines', category: 'Information', command: 'news' },
  { id: 59, name: 'Stock Prices', description: 'Real-time stock information', category: 'Information', command: 'stock price' },
  { id: 60, name: 'Dictionary', description: 'Word definitions', category: 'Information', command: 'define' },
  { id: 61, name: 'Thesaurus', description: 'Find synonyms', category: 'Information', command: 'synonym for' },
  { id: 62, name: 'Calculator', description: 'Perform calculations', category: 'Information', command: 'calculate' },
  { id: 63, name: 'Unit Converter', description: 'Convert units', category: 'Information', command: 'convert' },
  { id: 64, name: 'Currency Exchange', description: 'Currency conversion rates', category: 'Information', command: 'exchange rate' },
  { id: 65, name: 'Time Zone', description: 'World time zones', category: 'Information', command: 'time in' },
  { id: 66, name: 'Sports Scores', description: 'Live sports updates', category: 'Information', command: 'sports score' },
  { id: 67, name: 'Movie Info', description: 'Movie details and ratings', category: 'Information', command: 'movie info' },
  { id: 68, name: 'Book Recommendations', description: 'Suggest books to read', category: 'Information', command: 'recommend book' },
  { id: 69, name: 'Trivia', description: 'Random facts and trivia', category: 'Information', command: 'tell me trivia' },
  { id: 70, name: 'Quotes', description: 'Inspirational quotes', category: 'Information', command: 'quote' },
  { id: 71, name: 'Historical Events', description: 'Events on this day', category: 'Information', command: 'history today' },
  { id: 72, name: 'Science Facts', description: 'Scientific information', category: 'Information', command: 'science fact' },
  { id: 73, name: 'Math Solver', description: 'Solve mathematical problems', category: 'Information', command: 'solve math' },
  { id: 74, name: 'Periodic Table', description: 'Element information', category: 'Information', command: 'element' },
  { id: 75, name: 'Astronomy Data', description: 'Space and astronomy info', category: 'Information', command: 'astronomy' },
  { id: 76, name: 'Nutrition Info', description: 'Food nutrition facts', category: 'Information', command: 'nutrition' },
  { id: 77, name: 'Recipe Finder', description: 'Find cooking recipes', category: 'Information', command: 'recipe for' },
  { id: 78, name: 'Distance Calculator', description: 'Calculate distances', category: 'Information', command: 'distance from' },
  { id: 79, name: 'Population Data', description: 'World population statistics', category: 'Information', command: 'population of' },
  { id: 80, name: 'Country Info', description: 'Country facts', category: 'Information', command: 'country info' },
  { id: 81, name: 'Language Facts', description: 'Language information', category: 'Information', command: 'language info' },
  { id: 82, name: 'How-To Guides', description: 'Step-by-step instructions', category: 'Information', command: 'how to' },
  { id: 83, name: 'Code Snippet', description: 'Programming code examples', category: 'Information', command: 'code for' },
  { id: 84, name: 'Tech Specs', description: 'Technical specifications', category: 'Information', command: 'specs for' },
  { id: 85, name: 'Comparison Tool', description: 'Compare products/services', category: 'Information', command: 'compare' },

  // Entertainment (20 features)
  { id: 86, name: 'Play Music', description: 'Stream music', category: 'Entertainment', command: 'play music' },
  { id: 87, name: 'Podcast Player', description: 'Listen to podcasts', category: 'Entertainment', command: 'play podcast' },
  { id: 88, name: 'Radio', description: 'Stream radio stations', category: 'Entertainment', command: 'play radio' },
  { id: 89, name: 'Audiobook', description: 'Listen to audiobooks', category: 'Entertainment', command: 'play audiobook' },
  { id: 90, name: 'Game Launcher', description: 'Start interactive games', category: 'Entertainment', command: 'play game' },
  { id: 91, name: 'Joke Teller', description: 'Tell jokes', category: 'Entertainment', command: 'tell joke' },
  { id: 92, name: 'Story Generator', description: 'Create stories', category: 'Entertainment', command: 'tell story' },
  { id: 93, name: 'Movie Finder', description: 'Find movies to watch', category: 'Entertainment', command: 'find movie' },
  { id: 94, name: 'TV Guide', description: 'TV show schedules', category: 'Entertainment', command: 'tv guide' },
  { id: 95, name: 'Concert Finder', description: 'Upcoming concerts', category: 'Entertainment', command: 'concerts near me' },
  { id: 96, name: 'Event Discovery', description: 'Local events', category: 'Entertainment', command: 'events nearby' },
  { id: 97, name: 'Party Planner', description: 'Plan parties and events', category: 'Entertainment', command: 'plan party' },
  { id: 98, name: 'Karaoke Mode', description: 'Karaoke with lyrics', category: 'Entertainment', command: 'karaoke' },
  { id: 99, name: 'Playlist Creator', description: 'Create music playlists', category: 'Entertainment', command: 'create playlist' },
  { id: 100, name: 'Music Quiz', description: 'Test music knowledge', category: 'Entertainment', command: 'music quiz' },
  { id: 101, name: 'Movie Trivia', description: 'Movie trivia game', category: 'Entertainment', command: 'movie trivia' },
  { id: 102, name: 'Meditation Guide', description: 'Guided meditation', category: 'Entertainment', command: 'meditate' },
  { id: 103, name: 'White Noise', description: 'Ambient sounds', category: 'Entertainment', command: 'white noise' },
  { id: 104, name: 'Relaxation Sounds', description: 'Nature sounds', category: 'Entertainment', command: 'relaxation sounds' },
  { id: 105, name: 'Virtual DJ', description: 'Mix music tracks', category: 'Entertainment', command: 'dj mode' },

  // Smart Home (25 features)
  { id: 106, name: 'Lights Control', description: 'Control smart lights', category: 'Smart Home', command: 'lights on' },
  { id: 107, name: 'Thermostat', description: 'Adjust temperature', category: 'Smart Home', command: 'set temperature' },
  { id: 108, name: 'Lock Doors', description: 'Control smart locks', category: 'Smart Home', command: 'lock doors' },
  { id: 109, name: 'Security Camera', description: 'View security feeds', category: 'Smart Home', command: 'show cameras' },
  { id: 110, name: 'Alarm System', description: 'Control security alarm', category: 'Smart Home', command: 'arm alarm' },
  { id: 111, name: 'Garage Door', description: 'Open/close garage', category: 'Smart Home', command: 'garage door' },
  { id: 112, name: 'Blinds Control', description: 'Control smart blinds', category: 'Smart Home', command: 'open blinds' },
  { id: 113, name: 'Sprinkler System', description: 'Control lawn sprinklers', category: 'Smart Home', command: 'start sprinkler' },
  { id: 114, name: 'Appliance Control', description: 'Control smart appliances', category: 'Smart Home', command: 'start appliance' },
  { id: 115, name: 'Energy Monitor', description: 'Track energy usage', category: 'Smart Home', command: 'energy usage' },
  { id: 116, name: 'Scene Creator', description: 'Create automation scenes', category: 'Smart Home', command: 'create scene' },
  { id: 117, name: 'Doorbell Monitor', description: 'Smart doorbell alerts', category: 'Smart Home', command: 'doorbell' },
  { id: 118, name: 'Air Quality', description: 'Monitor air quality', category: 'Smart Home', command: 'air quality' },
  { id: 119, name: 'Humidity Control', description: 'Control humidity levels', category: 'Smart Home', command: 'set humidity' },
  { id: 120, name: 'Fan Control', description: 'Control smart fans', category: 'Smart Home', command: 'fan speed' },
  { id: 121, name: 'Water Leak Detector', description: 'Monitor water leaks', category: 'Smart Home', command: 'check leaks' },
  { id: 122, name: 'Smoke Detector', description: 'Monitor smoke alarms', category: 'Smart Home', command: 'smoke status' },
  { id: 123, name: 'Motion Sensors', description: 'Monitor motion detection', category: 'Smart Home', command: 'motion status' },
  { id: 124, name: 'Smart Plugs', description: 'Control outlet power', category: 'Smart Home', command: 'plug on' },
  { id: 125, name: 'Vacuum Robot', description: 'Control robot vacuum', category: 'Smart Home', command: 'start vacuum' },
  { id: 126, name: 'Home Status', description: 'Overall home status', category: 'Smart Home', command: 'home status' },
  { id: 127, name: 'Automation Rules', description: 'Create if-then rules', category: 'Smart Home', command: 'create rule' },
  { id: 128, name: 'Guest Mode', description: 'Enable guest access', category: 'Smart Home', command: 'guest mode' },
  { id: 129, name: 'Away Mode', description: 'Activate away settings', category: 'Smart Home', command: 'away mode' },
  { id: 130, name: 'Night Mode', description: 'Nighttime automation', category: 'Smart Home', command: 'night mode' },

  // Health & Fitness (25 features)
  { id: 131, name: 'Step Counter', description: 'Track daily steps', category: 'Health & Fitness', command: 'steps today' },
  { id: 132, name: 'Calorie Tracker', description: 'Track calorie intake', category: 'Health & Fitness', command: 'log calories' },
  { id: 133, name: 'Water Reminder', description: 'Hydration reminders', category: 'Health & Fitness', command: 'log water' },
  { id: 134, name: 'Sleep Tracker', description: 'Monitor sleep patterns', category: 'Health & Fitness', command: 'log sleep' },
  { id: 135, name: 'Workout Timer', description: 'Exercise timers', category: 'Health & Fitness', command: 'start workout' },
  { id: 136, name: 'Heart Rate', description: 'Monitor heart rate', category: 'Health & Fitness', command: 'heart rate' },
  { id: 137, name: 'BMI Calculator', description: 'Calculate body mass index', category: 'Health & Fitness', command: 'calculate bmi' },
  { id: 138, name: 'Meal Planner', description: 'Plan healthy meals', category: 'Health & Fitness', command: 'meal plan' },
  { id: 139, name: 'Medication Reminder', description: 'Track medications', category: 'Health & Fitness', command: 'remind medication' },
  { id: 140, name: 'Symptom Checker', description: 'Health symptom analysis', category: 'Health & Fitness', command: 'check symptoms' },
  { id: 141, name: 'Exercise Suggestions', description: 'Workout recommendations', category: 'Health & Fitness', command: 'suggest workout' },
  { id: 142, name: 'Yoga Guide', description: 'Yoga pose instructions', category: 'Health & Fitness', command: 'yoga pose' },
  { id: 143, name: 'Running Coach', description: 'Running training plans', category: 'Health & Fitness', command: 'running plan' },
  { id: 144, name: 'Weight Tracker', description: 'Track weight changes', category: 'Health & Fitness', command: 'log weight' },
  { id: 145, name: 'Blood Pressure', description: 'Monitor blood pressure', category: 'Health & Fitness', command: 'log bp' },
  { id: 146, name: 'Stress Monitor', description: 'Track stress levels', category: 'Health & Fitness', command: 'log stress' },
  { id: 147, name: 'Breathing Exercises', description: 'Guided breathing', category: 'Health & Fitness', command: 'breathing exercise' },
  { id: 148, name: 'Posture Reminder', description: 'Posture correction alerts', category: 'Health & Fitness', command: 'check posture' },
  { id: 149, name: 'Stretching Guide', description: 'Stretching routines', category: 'Health & Fitness', command: 'stretching routine' },
  { id: 150, name: 'Menstrual Tracker', description: 'Period tracking', category: 'Health & Fitness', command: 'log period' },
  { id: 151, name: 'Pregnancy Tracker', description: 'Pregnancy milestones', category: 'Health & Fitness', command: 'pregnancy week' },
  { id: 152, name: 'Vision Exercises', description: 'Eye health exercises', category: 'Health & Fitness', command: 'eye exercise' },
  { id: 153, name: 'Dental Reminder', description: 'Dental care reminders', category: 'Health & Fitness', command: 'dental reminder' },
  { id: 154, name: 'Skin Care Tracker', description: 'Skincare routine', category: 'Health & Fitness', command: 'skincare routine' },
  { id: 155, name: 'Mental Health', description: 'Mental wellness check', category: 'Health & Fitness', command: 'mood check' },

  // Finance (20 features)
  { id: 156, name: 'Budget Tracker', description: 'Track expenses', category: 'Finance', command: 'log expense' },
  { id: 157, name: 'Bill Reminder', description: 'Payment reminders', category: 'Finance', command: 'remind bill' },
  { id: 158, name: 'Investment Portfolio', description: 'Track investments', category: 'Finance', command: 'portfolio' },
  { id: 159, name: 'Crypto Prices', description: 'Cryptocurrency prices', category: 'Finance', command: 'crypto price' },
  { id: 160, name: 'Tax Calculator', description: 'Estimate taxes', category: 'Finance', command: 'calculate tax' },
  { id: 161, name: 'Savings Goals', description: 'Track savings targets', category: 'Finance', command: 'savings goal' },
  { id: 162, name: 'Loan Calculator', description: 'Calculate loan payments', category: 'Finance', command: 'loan calculator' },
  { id: 163, name: 'Receipt Scanner', description: 'Scan receipts', category: 'Finance', command: 'scan receipt' },
  { id: 164, name: 'Split Bill', description: 'Calculate bill splits', category: 'Finance', command: 'split bill' },
  { id: 165, name: 'Tip Calculator', description: 'Calculate tips', category: 'Finance', command: 'calculate tip' },
  { id: 166, name: 'Income Tracker', description: 'Track income sources', category: 'Finance', command: 'log income' },
  { id: 167, name: 'Financial Reports', description: 'Generate finance reports', category: 'Finance', command: 'financial report' },
  { id: 168, name: 'Subscription Manager', description: 'Track subscriptions', category: 'Finance', command: 'subscriptions' },
  { id: 169, name: 'Price Alerts', description: 'Stock price alerts', category: 'Finance', command: 'price alert' },
  { id: 170, name: 'Cashback Tracker', description: 'Track rewards', category: 'Finance', command: 'cashback' },
  { id: 171, name: 'Debt Payoff', description: 'Debt payoff calculator', category: 'Finance', command: 'debt payoff' },
  { id: 172, name: 'Retirement Planner', description: 'Retirement calculations', category: 'Finance', command: 'retirement plan' },
  { id: 173, name: 'Net Worth', description: 'Calculate net worth', category: 'Finance', command: 'net worth' },
  { id: 174, name: 'Financial News', description: 'Finance news updates', category: 'Finance', command: 'financial news' },
  { id: 175, name: 'Exchange Tracker', description: 'Track exchange rates', category: 'Finance', command: 'track exchange' },

  // Travel (15 features)
  { id: 176, name: 'Flight Search', description: 'Find flights', category: 'Travel', command: 'find flights' },
  { id: 177, name: 'Hotel Booking', description: 'Search hotels', category: 'Travel', command: 'find hotels' },
  { id: 178, name: 'Travel Itinerary', description: 'Organize trip plans', category: 'Travel', command: 'create itinerary' },
  { id: 179, name: 'Packing List', description: 'Travel packing checklist', category: 'Travel', command: 'packing list' },
  { id: 180, name: 'Visa Requirements', description: 'Check visa needs', category: 'Travel', command: 'visa info' },
  { id: 181, name: 'Travel Alerts', description: 'Safety and weather alerts', category: 'Travel', command: 'travel alerts' },
  { id: 182, name: 'Attraction Finder', description: 'Find attractions', category: 'Travel', command: 'attractions near' },
  { id: 183, name: 'Restaurant Finder', description: 'Find restaurants', category: 'Travel', command: 'restaurants nearby' },
  { id: 184, name: 'Translation', description: 'Translate languages', category: 'Travel', command: 'translate' },
  { id: 185, name: 'Currency Converter', description: 'Convert currency', category: 'Travel', command: 'currency convert' },
  { id: 186, name: 'Travel Budget', description: 'Track travel expenses', category: 'Travel', command: 'travel budget' },
  { id: 187, name: 'Trip Photos', description: 'Organize travel photos', category: 'Travel', command: 'organize photos' },
  { id: 188, name: 'Local Customs', description: 'Cultural information', category: 'Travel', command: 'local customs' },
  { id: 189, name: 'Emergency Contacts', description: 'Local emergency numbers', category: 'Travel', command: 'emergency numbers' },
  { id: 190, name: 'Travel Insurance', description: 'Insurance information', category: 'Travel', command: 'travel insurance' },

  // Education (15 features)
  { id: 191, name: 'Study Timer', description: 'Timed study sessions', category: 'Education', command: 'study session' },
  { id: 192, name: 'Flashcards', description: 'Digital flashcards', category: 'Education', command: 'create flashcard' },
  { id: 193, name: 'Quiz Generator', description: 'Create practice quizzes', category: 'Education', command: 'create quiz' },
  { id: 194, name: 'Essay Outline', description: 'Essay planning tool', category: 'Education', command: 'outline essay' },
  { id: 195, name: 'Research Assistant', description: 'Research help', category: 'Education', command: 'research' },
  { id: 196, name: 'Citation Generator', description: 'Create citations', category: 'Education', command: 'cite source' },
  { id: 197, name: 'Grammar Check', description: 'Check grammar', category: 'Education', command: 'check grammar' },
  { id: 198, name: 'Vocabulary Builder', description: 'Learn new words', category: 'Education', command: 'word of day' },
  { id: 199, name: 'Study Planner', description: 'Plan study schedule', category: 'Education', command: 'study plan' },
  { id: 200, name: 'Course Tracker', description: 'Track course progress', category: 'Education', command: 'track course' },
  { id: 201, name: 'Assignment Tracker', description: 'Track homework', category: 'Education', command: 'log assignment' },
  { id: 202, name: 'Grade Calculator', description: 'Calculate grades', category: 'Education', command: 'calculate grade' },
  { id: 203, name: 'Learning Resources', description: 'Find study materials', category: 'Education', command: 'find resources' },
  { id: 204, name: 'Exam Prep', description: 'Exam preparation', category: 'Education', command: 'exam prep' },
  { id: 205, name: 'Note Summarizer', description: 'Summarize notes', category: 'Education', command: 'summarize notes' },

  // Security (10 features)
  { id: 206, name: 'Password Generator', description: 'Generate secure passwords', category: 'Security', command: 'generate password' },
  { id: 207, name: 'Password Manager', description: 'Store passwords', category: 'Security', command: 'save password' },
  { id: 208, name: 'Two-Factor Auth', description: 'Manage 2FA codes', category: 'Security', command: '2fa code' },
  { id: 209, name: 'Security Audit', description: 'Check security status', category: 'Security', command: 'security audit' },
  { id: 210, name: 'Privacy Mode', description: 'Enhanced privacy', category: 'Security', command: 'privacy mode' },
  { id: 211, name: 'VPN Control', description: 'Manage VPN connection', category: 'Security', command: 'vpn on' },
  { id: 212, name: 'Encrypted Notes', description: 'Secure note storage', category: 'Security', command: 'secure note' },
  { id: 213, name: 'Biometric Lock', description: 'Biometric authentication', category: 'Security', command: 'enable biometric' },
  { id: 214, name: 'Device Locator', description: 'Find lost devices', category: 'Security', command: 'locate device' },
  { id: 215, name: 'Data Backup', description: 'Backup important data', category: 'Security', command: 'backup data' },

  // System Control (15 features)
  { id: 216, name: 'System Status', description: 'Check system health', category: 'System Control', command: 'system status' },
  { id: 217, name: 'Battery Status', description: 'Battery level check', category: 'System Control', command: 'battery' },
  { id: 218, name: 'Storage Info', description: 'Storage space info', category: 'System Control', command: 'storage' },
  { id: 219, name: 'Memory Usage', description: 'RAM usage stats', category: 'System Control', command: 'memory' },
  { id: 220, name: 'Network Status', description: 'Network connectivity', category: 'System Control', command: 'network status' },
  { id: 221, name: 'WiFi Manager', description: 'Manage WiFi', category: 'System Control', command: 'wifi' },
  { id: 222, name: 'Bluetooth Control', description: 'Bluetooth management', category: 'System Control', command: 'bluetooth' },
  { id: 223, name: 'Screen Brightness', description: 'Adjust brightness', category: 'System Control', command: 'brightness' },
  { id: 224, name: 'Volume Control', description: 'Adjust volume', category: 'System Control', command: 'volume' },
  { id: 225, name: 'Do Not Disturb', description: 'Silence notifications', category: 'System Control', command: 'do not disturb' },
  { id: 226, name: 'Airplane Mode', description: 'Toggle airplane mode', category: 'System Control', command: 'airplane mode' },
  { id: 227, name: 'Screen Record', description: 'Record screen', category: 'System Control', command: 'record screen' },
  { id: 228, name: 'Screenshot', description: 'Take screenshot', category: 'System Control', command: 'screenshot' },
  { id: 229, name: 'Power Options', description: 'Shutdown/restart', category: 'System Control', command: 'shutdown' },
  { id: 230, name: 'Update Check', description: 'Check for updates', category: 'System Control', command: 'check updates' },

  // Creative (15 features)
  { id: 231, name: 'Image Generator', description: 'Generate AI images', category: 'Creative', command: 'generate image' },
  { id: 232, name: 'Story Writer', description: 'Creative writing aid', category: 'Creative', command: 'write story' },
  { id: 233, name: 'Poetry Generator', description: 'Generate poems', category: 'Creative', command: 'write poem' },
  { id: 234, name: 'Music Composer', description: 'Compose melodies', category: 'Creative', command: 'compose music' },
  { id: 235, name: 'Color Palette', description: 'Color combinations', category: 'Creative', command: 'color palette' },
  { id: 236, name: 'Logo Designer', description: 'Logo ideas', category: 'Creative', command: 'design logo' },
  { id: 237, name: 'Drawing Assistant', description: 'Drawing tutorials', category: 'Creative', command: 'draw tutorial' },
  { id: 238, name: 'Video Editor', description: 'Edit videos', category: 'Creative', command: 'edit video' },
  { id: 239, name: 'Photo Filters', description: 'Apply photo effects', category: 'Creative', command: 'filter photo' },
  { id: 240, name: 'Name Generator', description: 'Generate names', category: 'Creative', command: 'generate name' },
  { id: 241, name: 'Brainstorming', description: 'Idea generation', category: 'Creative', command: 'brainstorm' },
  { id: 242, name: 'Mind Map', description: 'Create mind maps', category: 'Creative', command: 'mind map' },
  { id: 243, name: 'Character Creator', description: 'Create characters', category: 'Creative', command: 'create character' },
  { id: 244, name: 'Plot Generator', description: 'Story plot ideas', category: 'Creative', command: 'plot idea' },
  { id: 245, name: 'Rhyme Finder', description: 'Find rhyming words', category: 'Creative', command: 'rhyme with' },

  // Business (15 features)
  { id: 246, name: 'Meeting Scheduler', description: 'Schedule meetings', category: 'Business', command: 'schedule meeting' },
  { id: 247, name: 'Invoice Generator', description: 'Create invoices', category: 'Business', command: 'create invoice' },
  { id: 248, name: 'Client Manager', description: 'Manage clients', category: 'Business', command: 'add client' },
  { id: 249, name: 'Time Tracking', description: 'Billable hours', category: 'Business', command: 'track hours' },
  { id: 250, name: 'Proposal Writer', description: 'Business proposals', category: 'Business', command: 'write proposal' },
  { id: 251, name: 'Lead Tracker', description: 'Track sales leads', category: 'Business', command: 'add lead' },
  { id: 252, name: 'ROI Calculator', description: 'Return on investment', category: 'Business', command: 'calculate roi' },
  { id: 253, name: 'Business Plan', description: 'Business planning', category: 'Business', command: 'business plan' },
  { id: 254, name: 'Payroll Calculator', description: 'Calculate payroll', category: 'Business', command: 'calculate payroll' },
  { id: 255, name: 'Inventory Manager', description: 'Track inventory', category: 'Business', command: 'inventory' },
  { id: 256, name: 'Sales Analytics', description: 'Sales reports', category: 'Business', command: 'sales report' },
  { id: 257, name: 'Marketing Planner', description: 'Marketing strategies', category: 'Business', command: 'marketing plan' },
  { id: 258, name: 'Competitor Analysis', description: 'Analyze competitors', category: 'Business', command: 'analyze competitor' },
  { id: 259, name: 'Expense Reports', description: 'Business expenses', category: 'Business', command: 'expense report' },
  { id: 260, name: 'Contract Templates', description: 'Legal contracts', category: 'Business', command: 'contract template' },

  // Social Media (10 features)
  { id: 261, name: 'Post Scheduler', description: 'Schedule posts', category: 'Social Media', command: 'schedule post' },
  { id: 262, name: 'Hashtag Generator', description: 'Generate hashtags', category: 'Social Media', command: 'hashtags for' },
  { id: 263, name: 'Caption Writer', description: 'Write captions', category: 'Social Media', command: 'write caption' },
  { id: 264, name: 'Analytics Dashboard', description: 'Social media stats', category: 'Social Media', command: 'social stats' },
  { id: 265, name: 'Engagement Tracker', description: 'Track engagement', category: 'Social Media', command: 'track engagement' },
  { id: 266, name: 'Content Calendar', description: 'Plan content', category: 'Social Media', command: 'content calendar' },
  { id: 267, name: 'Trend Monitor', description: 'Track trends', category: 'Social Media', command: 'trending topics' },
  { id: 268, name: 'Image Resizer', description: 'Resize for platforms', category: 'Social Media', command: 'resize image' },
  { id: 269, name: 'Bio Generator', description: 'Create bios', category: 'Social Media', command: 'generate bio' },
  { id: 270, name: 'Link Shortener', description: 'Shorten URLs', category: 'Social Media', command: 'shorten link' },

  // Shopping (10 features)
  { id: 271, name: 'Shopping List', description: 'Create shopping lists', category: 'Shopping', command: 'shopping list' },
  { id: 272, name: 'Price Comparison', description: 'Compare prices', category: 'Shopping', command: 'compare prices' },
  { id: 273, name: 'Deal Finder', description: 'Find deals', category: 'Shopping', command: 'find deals' },
  { id: 274, name: 'Product Reviews', description: 'Read reviews', category: 'Shopping', command: 'product reviews' },
  { id: 275, name: 'Wishlist Manager', description: 'Manage wishlists', category: 'Shopping', command: 'add wishlist' },
  { id: 276, name: 'Coupon Finder', description: 'Find coupons', category: 'Shopping', command: 'find coupons' },
  { id: 277, name: 'Size Guide', description: 'Size recommendations', category: 'Shopping', command: 'size guide' },
  { id: 278, name: 'Barcode Scanner', description: 'Scan products', category: 'Shopping', command: 'scan barcode' },
  { id: 279, name: 'Order Tracker', description: 'Track deliveries', category: 'Shopping', command: 'track order' },
  { id: 280, name: 'Return Manager', description: 'Manage returns', category: 'Shopping', command: 'return item' },

  // Weather & Environment (10 features)
  { id: 281, name: 'Weather Forecast', description: 'Current weather', category: 'Weather & Environment', command: 'weather' },
  { id: 282, name: 'Extended Forecast', description: '7-day forecast', category: 'Weather & Environment', command: 'forecast' },
  { id: 283, name: 'Severe Alerts', description: 'Weather warnings', category: 'Weather & Environment', command: 'weather alerts' },
  { id: 284, name: 'UV Index', description: 'Sun exposure info', category: 'Weather & Environment', command: 'uv index' },
  { id: 285, name: 'Pollen Count', description: 'Allergy information', category: 'Weather & Environment', command: 'pollen count' },
  { id: 286, name: 'Air Quality Index', description: 'Air pollution levels', category: 'Weather & Environment', command: 'air quality' },
  { id: 287, name: 'Sunrise/Sunset', description: 'Sun times', category: 'Weather & Environment', command: 'sunrise' },
  { id: 288, name: 'Moon Phase', description: 'Lunar calendar', category: 'Weather & Environment', command: 'moon phase' },
  { id: 289, name: 'Earthquake Monitor', description: 'Seismic activity', category: 'Weather & Environment', command: 'earthquakes' },
  { id: 290, name: 'Environmental News', description: 'Eco news', category: 'Weather & Environment', command: 'eco news' },

  // Navigation (5 features)
  { id: 291, name: 'GPS Navigation', description: 'Turn-by-turn directions', category: 'Navigation', command: 'navigate to' },
  { id: 292, name: 'Traffic Updates', description: 'Real-time traffic', category: 'Navigation', command: 'traffic' },
  { id: 293, name: 'Parking Finder', description: 'Find parking', category: 'Navigation', command: 'find parking' },
  { id: 294, name: 'Public Transit', description: 'Transit schedules', category: 'Navigation', command: 'transit route' },
  { id: 295, name: 'Points of Interest', description: 'Nearby places', category: 'Navigation', command: 'places nearby' },

  // Personal Assistant (15 features)
  { id: 296, name: 'Daily Briefing', description: 'Morning summary', category: 'Personal Assistant', command: 'daily briefing' },
  { id: 297, name: 'Smart Suggestions', description: 'AI recommendations', category: 'Personal Assistant', command: 'suggestions' },
  { id: 298, name: 'Context Awareness', description: 'Understand context', category: 'Personal Assistant', command: 'context' },
  { id: 299, name: 'Routine Builder', description: 'Create routines', category: 'Personal Assistant', command: 'create routine' },
  { id: 300, name: 'Personal Insights', description: 'Behavior analytics', category: 'Personal Assistant', command: 'insights' },
  { id: 301, name: 'Smart Reminders', description: 'Context-based reminders', category: 'Personal Assistant', command: 'smart remind' },
  { id: 302, name: 'Decision Helper', description: 'Help make decisions', category: 'Personal Assistant', command: 'help decide' },
  { id: 303, name: 'Life Coach', description: 'Personal coaching', category: 'Personal Assistant', command: 'life advice' },
  { id: 304, name: 'Memory Palace', description: 'Remember things', category: 'Personal Assistant', command: 'remember' },
  { id: 305, name: 'Relationship Manager', description: 'Track relationships', category: 'Personal Assistant', command: 'relationship' },

  // Data Analysis (5 features)
  { id: 306, name: 'Data Visualizer', description: 'Create charts', category: 'Data Analysis', command: 'visualize data' },
  { id: 307, name: 'Trend Analyzer', description: 'Analyze trends', category: 'Data Analysis', command: 'analyze trends' },
  { id: 308, name: 'Statistics Calculator', description: 'Statistical analysis', category: 'Data Analysis', command: 'statistics' },
  { id: 309, name: 'Prediction Model', description: 'Predictive analytics', category: 'Data Analysis', command: 'predict' },
  { id: 310, name: 'Report Generator', description: 'Auto-generate reports', category: 'Data Analysis', command: 'generate report' },

  // Automation (5 features)
  { id: 311, name: 'Workflow Automation', description: 'Automate tasks', category: 'Automation', command: 'automate' },
  { id: 312, name: 'IFTTT Integration', description: 'If-this-then-that', category: 'Automation', command: 'ifttt' },
  { id: 313, name: 'Macro Recorder', description: 'Record actions', category: 'Automation', command: 'record macro' },
  { id: 314, name: 'Schedule Tasks', description: 'Cron-like scheduling', category: 'Automation', command: 'schedule task' },
  { id: 315, name: 'Batch Operations', description: 'Bulk actions', category: 'Automation', command: 'batch execute' },
];
